---
name: Generate terraform docs

on:
  pull_request:
  workflow_dispatch:

jobs:
  terraform-docs:
    name: docs

    runs-on: ubuntu-latest

    steps:
    - name: Check out the codebase
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs inside the README.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@v1.1.0
      with:
        working-dir: .
        output-file: README.md
        output-method: inject
        git-push: "true"
